In [3]:
import pandas as pd

In [4]:
pd.read_csv('./../data/gapminder_full.csv')

          country  year  population continent  life_exp     gdp_cap
0     Afghanistan  1952     8425333      Asia    28.801  779.445314
1     Afghanistan  1957     9240934      Asia    30.332  820.853030
2     Afghanistan  1962    10267083      Asia    31.997  853.100710
3     Afghanistan  1967    11537966      Asia    34.020  836.197138
4     Afghanistan  1972    13079460      Asia    36.088  739.981106
...           ...   ...         ...       ...       ...         ...
1699     Zimbabwe  1987     9216418    Africa    62.351  706.157306
1700     Zimbabwe  1992    10704340    Africa    60.377  693.420786
1701     Zimbabwe  1997    11404948    Africa    46.809  792.449960
1702     Zimbabwe  2002    11926563    Africa    39.989  672.038623
1703     Zimbabwe  2007    12311143    Africa    43.487  469.709298

[1704 rows x 6 columns]

In [5]:
# renombro mi archivo de datos
gapminder = pd.read_csv('./../data/gapminder_full.csv')

In [6]:
#ahora veo los nombres de las columnas
gapminder.head()

       country  year  population continent  life_exp     gdp_cap
0  Afghanistan  1952     8425333      Asia    28.801  779.445314
1  Afghanistan  1957     9240934      Asia    30.332  820.853030
2  Afghanistan  1962    10267083      Asia    31.997  853.100710
3  Afghanistan  1967    11537966      Asia    34.020  836.197138
4  Afghanistan  1972    13079460      Asia    36.088  739.981106

Explorando los datos

In [7]:
#primero vemos la forma que tiene la tabla
gapminder.shape

(1704, 6)

In [8]:
# ahora veo el tipo de datos por cada variable
gapminder.dtypes

country        object
year            int64
population      int64
continent      object
life_exp      float64
gdp_cap       float64
dtype: object

In [ ]:
# ahora debemos hacer preguntas sobre cada variable (columna) para empezar a ver como 
# las vamos a responder

# En este ejemplo podemos hacer preguntas sobre cada columna, 
# para country.
# Â¿cuantos paises hay en 2007?
# cuantos paises por continente

# preguntas sobre year
# de que aÃ±o a que aÃ±o van los datos
# cuatos datos hay por aÃ±o

# preguntas sobre poblaciÃ³n
# Â¿cual es la poblaciÃ³n minima y maxima?
# cual es la poblaciÃ³n mundial por aÃ±o
# cual es el pais con mayor y enor poblacion en 2007
# cual es la poblaciÃ³n para un pais especifico en 2007
# cual es la poblacion por continente para el aÃ±o 2007
# Â¿como se distrubuye la poblaciÃ±on por aÃ±o (histograma)?

# preguntas sobre continente
# Â¿cuales continentes hay?
# cuantos paises hay en cada contienente para 2007

# preguntas sobre life_exp
# cuales son los minimos y maximos life_exp para un aÃ±o especifico
# como se distribuye el promedio de life_exp por contienete para el Ãºltimo aÃ±o
# cual es el life_exp por pais para 2007

# preguntas sobre gdp_cap
# Â¿cual es el gdp_cap por pais?
# Â¿cual es el gdp_cap por continente?
# como se distrubuye el gdp per capita para el aÃ±o 2007 (cuantiles)

# otras buscando relaciones entre las variables
# a moyor life_exp mayor gdp_cap
# a mayor poblacion mayor ilfe_exp
# a mayor poblacion mayor gdp_cap
# a mayor aÃ±o mayor life_exp, aumenta life_exp con los aÃ±os
# a mayor aÃ±o, mayor gdp_cap, aumenta gdp_cap con los aÃ±os

In [9]:
# leo mis datos
pd.read_csv('./../data/Sentiment.csv')

,id,candidate,candidate_confidence,relevant_yn,relevant_yn_confidence,sentiment,sentiment_confidence,subject_matter,subject_matter_confidence,candidate_gold,...,relevant_yn_gold,retweet_count,sentiment_gold,subject_matter_gold,text,tweet_coord,tweet_created,tweet_id,tweet_location,user_timezone
0,1,No candidate mentioned,1.0000,yes,1.0000,Neutral,0.6578,None of the above,1.0000,NaN,...,NaN,5,NaN,NaN,RT @NancyLeeGrahn: How did everyone feel about...,NaN,2015-08-07 09:54:46 -0700,629697200650592256,NaN,Quito
1,2,Scott Walker,1.0000,yes,1.0000,Positive,0.6333,None of the above,1.0000,NaN,...,NaN,26,NaN,NaN,RT @ScottWalker: Didn't catch the full #GOPdeb...,NaN,2015-08-07 09:54:46 -0700,629697199560069120,NaN,NaN
2,3,No candidate mentioned,1.0000,yes,1.0000,Neutral,0.6629,None of the above,0.6629,NaN,...,NaN,27,NaN,NaN,RT @TJMShow: No mention of Tamir Rice and the ...,NaN,2015-08-07 09:54:46 -0700,629697199312482304,NaN,NaN
3,4,No candidate mentioned,1.0000,yes,1.0000,Positive,1.0000,None of the above,0.7039,NaN,...,NaN,138,NaN,NaN,RT @RobGeorge: That Carly Fiorina is trending ...,NaN,2015-08-07 09:54:45 -0700,629697197118861312,Texas,Central Time (US & Canada)
4,5,Donald Trump,1.0000,yes,1.0000,Positive,0.7045,None of the above,1.0000,NaN,...,NaN,156,NaN,NaN,RT @DanScavino: #GOPDebate w/ @realDonaldTrump...,NaN,2015-08-07 09:54:45 -0700,629697196967903232,NaN,Arizona
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
13866,13867,No candidate mentioned,1.0000,yes,1.0000,Negative,0.7991,Abortion,0.6014,No candidate mentioned,...,yes,7,Negative,Abortion\nWomen's Issues (not abortion though),RT @cappy_yarbrough: Love to see men who will ...,NaN,2015-08-07 09:29:43 -0700,629690895479250944,Como,NaN
13867,13868,Mike Huckabee,0.9611,yes,1.0000,Positive,0.7302,None of the above,0.9229,Mike Huckabee,...,yes,1,NaN,NaN,RT @georgehenryw: Who thought Huckabee exceede...,NaN,2015-08-07 09:25:02 -0700,629689719056568320,USA,NaN
13868,13869,Ted Cruz,1.0000,yes,1.0000,Positive,0.8051,None of the above,0.9647,Ted Cruz,...,yes,67,Positive\nNeutral,NaN,"RT @Lrihendry: #TedCruz As President, I will a...",NaN,2015-08-07 07:19:18 -0700,629658075784282112,NaN,NaN
13869,13870,Donald Trump,1.0000,yes,1.0000,Negative,1.0000,Women's Issues (not abortion though),0.9202,Donald Trump,...,yes,149,NaN,Women's Issues (not abortion though),RT @JRehling: #GOPDebate Donald Trump says tha...,NaN,2015-08-07 09:54:04 -0700,629697023663546368,NaN,NaN
13870,13871,Ted Cruz,0.9242,yes,0.9614,Positive,0.9614,None of the above,0.9242,Ted Cruz,...,yes,65,Positive,NaN,RT @Lrihendry: #TedCruz headed into the Presid...,NaN,2015-08-06 18:22:27 -0700,629462573641920512,"San Antonio, TX",Central Time (US & Canada)

In [10]:
# Renombro mis datos
sentimientos = pd.read_csv('./../data/Sentiment.csv')

In [16]:
# Veo los nombres de las columnas
sentimientos.head()

,id,candidate,candidate_confidence,relevant_yn,relevant_yn_confidence,sentiment,sentiment_confidence,subject_matter,subject_matter_confidence,candidate_gold,...,relevant_yn_gold,retweet_count,sentiment_gold,subject_matter_gold,text,tweet_coord,tweet_created,tweet_id,tweet_location,user_timezone
0,1,No candidate mentioned,1.0,yes,1.0,Neutral,0.6578,None of the above,1.0000,NaN,...,NaN,5,NaN,NaN,RT @NancyLeeGrahn: How did everyone feel about...,NaN,2015-08-07 09:54:46 -0700,629697200650592256,NaN,Quito
1,2,Scott Walker,1.0,yes,1.0,Positive,0.6333,None of the above,1.0000,NaN,...,NaN,26,NaN,NaN,RT @ScottWalker: Didn't catch the full #GOPdeb...,NaN,2015-08-07 09:54:46 -0700,629697199560069120,NaN,NaN
2,3,No candidate mentioned,1.0,yes,1.0,Neutral,0.6629,None of the above,0.6629,NaN,...,NaN,27,NaN,NaN,RT @TJMShow: No mention of Tamir Rice and the ...,NaN,2015-08-07 09:54:46 -0700,629697199312482304,NaN,NaN
3,4,No candidate mentioned,1.0,yes,1.0,Positive,1.0000,None of the above,0.7039,NaN,...,NaN,138,NaN,NaN,RT @RobGeorge: That Carly Fiorina is trending ...,NaN,2015-08-07 09:54:45 -0700,629697197118861312,Texas,Central Time (US & Canada)
4,5,Donald Trump,1.0,yes,1.0,Positive,0.7045,None of the above,1.0000,NaN,...,NaN,156,NaN,NaN,RT @DanScavino: #GOPDebate w/ @realDonaldTrump...,NaN,2015-08-07 09:54:45 -0700,629697196967903232,NaN,Arizona

In [17]:
# veo de cuantos datos esta hecho mi dataframe
sentimientos.shape

(13871, 21)

In [18]:
sentimientos.dtypes

id                             int64
candidate                     object
candidate_confidence         float64
relevant_yn                   object
relevant_yn_confidence       float64
sentiment                     object
sentiment_confidence         float64
subject_matter                object
subject_matter_confidence    float64
candidate_gold                object
name                          object
relevant_yn_gold              object
retweet_count                  int64
sentiment_gold                object
subject_matter_gold           object
text                          object
tweet_coord                   object
tweet_created                 object
tweet_id                       int64
tweet_location                object
user_timezone                 object
dtype: object

In [ ]:
#Columna id
#Es solo un indicador 

#Candidato
#Este el nombre del candidato mencionado en el tweet
#Â¿QuÃ© candidato se repite mas en esta columna?
#Â¿CuÃ¡ntos candidatos diferentes hay en esta lista?
#Â¿que candidato se repite mas y cual menos?

#Confianza en el candidato
#Â¿QuÃ© candidato tiene mas tweets con este numero alto?
#Â¿QuÃ© candidato tiene mas tweets con este numero pequeÃ±o?

#Sentimiento
#Solo puede tomar 3 valores, negativo, positivo y neutral
#Â¿CuÃ¡ntos tweets hay con cada calificaciÃ³n, positivo, negativo y neutro?

#Tema en cuestiÃ³n _ subject matter
#Â¿QuÃ© tema se repite mas veces y cual menos veces?
#Â¿QuÃ© tema tiene mas tweets?
#Â¿QuÃ© tema tiene mas positivos, negativos o neutros?

#Name
#Nombre de la persona que hizo el tweet
#Â¿QuÃ© persona es una persona y cual no?
#Â¿CuÃ¡ntos tweets hace esa persona y a quien menciona?

#Cuenta de retweets
#Â¿QuÃ© tweets tiene mayor a menor cantidad de retweets?
#Â¿QuÃ© tema habla de cierto candidato y tiene mas o menos retweets?

#Tweet created
#Dice cuando se hizo el tweet
#Â¿CuÃ¡nto tiempo pasa entre tweet y tweet sobre un tema?
#Â¿CuÃ¡nto tiempo pasa entre un tweet y su retweet???
#Â¿entre que horario hay mas tweets?
#Â¿en que dÃ­a hay mÃ¡s tweets?

#Tweet location
#Dice donde se hace el tweet
#Â¿QuÃ© lugar tiene mas tweets?

# Â¿quÃ© candidadto tiene mas tweets, buenos malos y neutros?

# TÃ­tulo

descripciÃ³n