In [1]:
import pandas as pd

In [4]:
pd.read_csv('./../data/gapminder_full.csv')

          country  year  population continent  life_exp     gdp_cap
0     Afghanistan  1952     8425333      Asia    28.801  779.445314
1     Afghanistan  1957     9240934      Asia    30.332  820.853030
2     Afghanistan  1962    10267083      Asia    31.997  853.100710
3     Afghanistan  1967    11537966      Asia    34.020  836.197138
4     Afghanistan  1972    13079460      Asia    36.088  739.981106
...           ...   ...         ...       ...       ...         ...
1699     Zimbabwe  1987     9216418    Africa    62.351  706.157306
1700     Zimbabwe  1992    10704340    Africa    60.377  693.420786
1701     Zimbabwe  1997    11404948    Africa    46.809  792.449960
1702     Zimbabwe  2002    11926563    Africa    39.989  672.038623
1703     Zimbabwe  2007    12311143    Africa    43.487  469.709298

[1704 rows x 6 columns]

In [5]:
# renombro mi archivo de datos
gapminder = pd.read_csv('./../data/gapminder_full.csv')

In [6]:
#ahora veo los nombres de las columnas
gapminder.head()

       country  year  population continent  life_exp     gdp_cap
0  Afghanistan  1952     8425333      Asia    28.801  779.445314
1  Afghanistan  1957     9240934      Asia    30.332  820.853030
2  Afghanistan  1962    10267083      Asia    31.997  853.100710
3  Afghanistan  1967    11537966      Asia    34.020  836.197138
4  Afghanistan  1972    13079460      Asia    36.088  739.981106

Explorando los datos

In [7]:
#primero vemos la forma que tiene la tabla
gapminder.shape

(1704, 6)

In [8]:
# ahora veo el tipo de datos por cada variable
gapminder.dtypes

country        object
year            int64
population      int64
continent      object
life_exp      float64
gdp_cap       float64
dtype: object

In [ ]:
# ahora debemos hacer preguntas sobre cada variable (columna) para empezar a ver como 
# las vamos a responder

# En este ejemplo podemos hacer preguntas sobre cada columna, 
# para country.
# Â¿cuantos paises hay en 2007?
# cuantos paises por continente

# preguntas sobre year
# de que aÃ±o a que aÃ±o van los datos
# cuatos datos hay por aÃ±o

# preguntas sobre poblaciÃ³n
# Â¿cual es la poblaciÃ³n minima y maxima?
# cual es la poblaciÃ³n mundial por aÃ±o
# cual es el pais con mayor y enor poblacion en 2007
# cual es la poblaciÃ³n para un pais especifico en 2007
# cual es la poblacion por continente para el aÃ±o 2007
# Â¿como se distrubuye la poblaciÃ±on por aÃ±o (histograma)?

# preguntas sobre continente
# Â¿cuales continentes hay?
# cuantos paises hay en cada contienente para 2007

# preguntas sobre life_exp
# cuales son los minimos y maximos life_exp para un aÃ±o especifico
# como se distribuye el promedio de life_exp por contienete para el Ãºltimo aÃ±o
# cual es el life_exp por pais para 2007

# preguntas sobre gdp_cap
# Â¿cual es el gdp_cap por pais?
# Â¿cual es el gdp_cap por continente?
# como se distrubuye el gdp per capita para el aÃ±o 2007 (cuantiles)

# otras buscando relaciones entre las variables
# a moyor life_exp mayor gdp_cap
# a mayor poblacion mayor ilfe_exp
# a mayor poblacion mayor gdp_cap
# a mayor aÃ±o mayor life_exp, aumenta life_exp con los aÃ±os
# a mayor aÃ±o, mayor gdp_cap, aumenta gdp_cap con los aÃ±os

In [2]:
# leo mis datos
pd.read_csv('./../data/Sentiment.csv')

,id,candidate,candidate_confidence,relevant_yn,relevant_yn_confidence,sentiment,sentiment_confidence,subject_matter,subject_matter_confidence,candidate_gold,...,relevant_yn_gold,retweet_count,sentiment_gold,subject_matter_gold,text,tweet_coord,tweet_created,tweet_id,tweet_location,user_timezone
0,1,No candidate mentioned,1.0000,yes,1.0000,Neutral,0.6578,None of the above,1.0000,NaN,...,NaN,5,NaN,NaN,RT @NancyLeeGrahn: How did everyone feel about...,NaN,2015-08-07 09:54:46 -0700,629697200650592256,NaN,Quito
1,2,Scott Walker,1.0000,yes,1.0000,Positive,0.6333,None of the above,1.0000,NaN,...,NaN,26,NaN,NaN,RT @ScottWalker: Didn't catch the full #GOPdeb...,NaN,2015-08-07 09:54:46 -0700,629697199560069120,NaN,NaN
2,3,No candidate mentioned,1.0000,yes,1.0000,Neutral,0.6629,None of the above,0.6629,NaN,...,NaN,27,NaN,NaN,RT @TJMShow: No mention of Tamir Rice and the ...,NaN,2015-08-07 09:54:46 -0700,629697199312482304,NaN,NaN
3,4,No candidate mentioned,1.0000,yes,1.0000,Positive,1.0000,None of the above,0.7039,NaN,...,NaN,138,NaN,NaN,RT @RobGeorge: That Carly Fiorina is trending ...,NaN,2015-08-07 09:54:45 -0700,629697197118861312,Texas,Central Time (US & Canada)
4,5,Donald Trump,1.0000,yes,1.0000,Positive,0.7045,None of the above,1.0000,NaN,...,NaN,156,NaN,NaN,RT @DanScavino: #GOPDebate w/ @realDonaldTrump...,NaN,2015-08-07 09:54:45 -0700,629697196967903232,NaN,Arizona
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
13866,13867,No candidate mentioned,1.0000,yes,1.0000,Negative,0.7991,Abortion,0.6014,No candidate mentioned,...,yes,7,Negative,Abortion\nWomen's Issues (not abortion though),RT @cappy_yarbrough: Love to see men who will ...,NaN,2015-08-07 09:29:43 -0700,629690895479250944,Como,NaN
13867,13868,Mike Huckabee,0.9611,yes,1.0000,Positive,0.7302,None of the above,0.9229,Mike Huckabee,...,yes,1,NaN,NaN,RT @georgehenryw: Who thought Huckabee exceede...,NaN,2015-08-07 09:25:02 -0700,629689719056568320,USA,NaN
13868,13869,Ted Cruz,1.0000,yes,1.0000,Positive,0.8051,None of the above,0.9647,Ted Cruz,...,yes,67,Positive\nNeutral,NaN,"RT @Lrihendry: #TedCruz As President, I will a...",NaN,2015-08-07 07:19:18 -0700,629658075784282112,NaN,NaN
13869,13870,Donald Trump,1.0000,yes,1.0000,Negative,1.0000,Women's Issues (not abortion though),0.9202,Donald Trump,...,yes,149,NaN,Women's Issues (not abortion though),RT @JRehling: #GOPDebate Donald Trump says tha...,NaN,2015-08-07 09:54:04 -0700,629697023663546368,NaN,NaN
13870,13871,Ted Cruz,0.9242,yes,0.9614,Positive,0.9614,None of the above,0.9242,Ted Cruz,...,yes,65,Positive,NaN,RT @Lrihendry: #TedCruz headed into the Presid...,NaN,2015-08-06 18:22:27 -0700,629462573641920512,"San Antonio, TX",Central Time (US & Canada)

In [3]:
# Renombro mis datos
sentimientos = pd.read_csv('./../data/Sentiment.csv')

In [4]:
# Veo los nombres de las columnas
sentimientos.head()

,id,candidate,candidate_confidence,relevant_yn,relevant_yn_confidence,sentiment,sentiment_confidence,subject_matter,subject_matter_confidence,candidate_gold,...,relevant_yn_gold,retweet_count,sentiment_gold,subject_matter_gold,text,tweet_coord,tweet_created,tweet_id,tweet_location,user_timezone
0,1,No candidate mentioned,1.0,yes,1.0,Neutral,0.6578,None of the above,1.0000,NaN,...,NaN,5,NaN,NaN,RT @NancyLeeGrahn: How did everyone feel about...,NaN,2015-08-07 09:54:46 -0700,629697200650592256,NaN,Quito
1,2,Scott Walker,1.0,yes,1.0,Positive,0.6333,None of the above,1.0000,NaN,...,NaN,26,NaN,NaN,RT @ScottWalker: Didn't catch the full #GOPdeb...,NaN,2015-08-07 09:54:46 -0700,629697199560069120,NaN,NaN
2,3,No candidate mentioned,1.0,yes,1.0,Neutral,0.6629,None of the above,0.6629,NaN,...,NaN,27,NaN,NaN,RT @TJMShow: No mention of Tamir Rice and the ...,NaN,2015-08-07 09:54:46 -0700,629697199312482304,NaN,NaN
3,4,No candidate mentioned,1.0,yes,1.0,Positive,1.0000,None of the above,0.7039,NaN,...,NaN,138,NaN,NaN,RT @RobGeorge: That Carly Fiorina is trending ...,NaN,2015-08-07 09:54:45 -0700,629697197118861312,Texas,Central Time (US & Canada)
4,5,Donald Trump,1.0,yes,1.0,Positive,0.7045,None of the above,1.0000,NaN,...,NaN,156,NaN,NaN,RT @DanScavino: #GOPDebate w/ @realDonaldTrump...,NaN,2015-08-07 09:54:45 -0700,629697196967903232,NaN,Arizona

In [5]:
# veo de cuantos datos esta hecho mi dataframe
sentimientos.shape

(13871, 21)

In [6]:
sentimientos.dtypes

id                             int64
candidate                     object
candidate_confidence         float64
relevant_yn                   object
relevant_yn_confidence       float64
sentiment                     object
sentiment_confidence         float64
subject_matter                object
subject_matter_confidence    float64
candidate_gold                object
name                          object
relevant_yn_gold              object
retweet_count                  int64
sentiment_gold                object
subject_matter_gold           object
text                          object
tweet_coord                   object
tweet_created                 object
tweet_id                       int64
tweet_location                object
user_timezone                 object
dtype: object

In [ ]:
#Columna id
#Es solo un indicador 

#Candidato
#Este el nombre del candidato mencionado en el tweet
#Â¿QuÃ© candidato se repite mas en esta columna?
#Â¿CuÃ¡ntos candidatos diferentes hay en esta lista?
#Â¿que candidato se repite mas y cual menos?

#Confianza en el candidato
#Â¿QuÃ© candidato tiene mas tweets con este numero alto?
#Â¿QuÃ© candidato tiene mas tweets con este numero pequeÃ±o?

#Sentimiento
#Solo puede tomar 3 valores, negativo, positivo y neutral
#Â¿CuÃ¡ntos tweets hay con cada calificaciÃ³n, positivo, negativo y neutro?

#Tema en cuestiÃ³n _ subject matter
#Â¿QuÃ© tema se repite mas veces y cual menos veces?
#Â¿QuÃ© tema tiene mas tweets?
#Â¿QuÃ© tema tiene mas positivos, negativos o neutros?

#Name
#Nombre de la persona que hizo el tweet
#Â¿QuÃ© persona es una persona y cual no?
#Â¿CuÃ¡ntos tweets hace esa persona y a quien menciona?

#Cuenta de retweets
#Â¿QuÃ© tweets tiene mayor a menor cantidad de retweets?
#Â¿QuÃ© tema habla de cierto candidato y tiene mas o menos retweets?

#Tweet created
#Dice cuando se hizo el tweet
#Â¿CuÃ¡nto tiempo pasa entre tweet y tweet sobre un tema?
#Â¿CuÃ¡nto tiempo pasa entre un tweet y su retweet???
#Â¿entre que horario hay mas tweets?
#Â¿en que dÃ­a hay mÃ¡s tweets?

#Tweet location
#Dice donde se hace el tweet
#Â¿QuÃ© lugar tiene mas tweets?

# Â¿quÃ© candidadto tiene mas tweets, buenos malos y neutros?

# TÃ­tulo

descripciÃ³n

In [7]:
sentimientos.count()

id                           13871
candidate                    13775
candidate_confidence         13871
relevant_yn                  13871
relevant_yn_confidence       13871
sentiment                    13871
sentiment_confidence         13871
subject_matter               13545
subject_matter_confidence    13871
candidate_gold                  28
name                         13871
relevant_yn_gold                32
retweet_count                13871
sentiment_gold                  15
subject_matter_gold             18
text                         13871
tweet_coord                     21
tweet_created                13871
tweet_id                     13871
tweet_location                9959
user_timezone                 9468
dtype: int64

In [12]:
sentimientos[['candidate','sentiment','subject_matter','name','retweet_count','tweet_created',
               'tweet_location']]

,candidate,sentiment,subject_matter,name,retweet_count,tweet_created,tweet_location
0,No candidate mentioned,Neutral,None of the above,I_Am_Kenzi,5,2015-08-07 09:54:46 -0700,NaN
1,Scott Walker,Positive,None of the above,PeacefulQuest,26,2015-08-07 09:54:46 -0700,NaN
2,No candidate mentioned,Neutral,None of the above,PussssyCroook,27,2015-08-07 09:54:46 -0700,NaN
3,No candidate mentioned,Positive,None of the above,MattFromTexas31,138,2015-08-07 09:54:45 -0700,Texas
4,Donald Trump,Positive,None of the above,sharonDay5,156,2015-08-07 09:54:45 -0700,NaN
...,...,...,...,...,...,...,...
13866,No candidate mentioned,Negative,Abortion,SantoliDonato,7,2015-08-07 09:29:43 -0700,Como
13867,Mike Huckabee,Positive,None of the above,mhfa16hq,1,2015-08-07 09:25:02 -0700,USA
13868,Ted Cruz,Positive,None of the above,DrottM,67,2015-08-07 07:19:18 -0700,NaN
13869,Donald Trump,Negative,Women's Issues (not abortion though),danijeantheq,149,2015-08-07 09:54:04 -0700,NaN
13870,Ted Cruz,Positive,None of the above,MichaelHuff52,65,2015-08-06 18:22:27 -0700,"San Antonio, TX"

In [13]:
sentimientos_filtrado = sentimientos[['candidate','sentiment','subject_matter','name','retweet_count','tweet_created',
               'tweet_location']]

In [14]:
sentimientos_filtrado.head(5)

,candidate,sentiment,subject_matter,name,retweet_count,tweet_created,tweet_location
0,No candidate mentioned,Neutral,None of the above,I_Am_Kenzi,5,2015-08-07 09:54:46 -0700,NaN
1,Scott Walker,Positive,None of the above,PeacefulQuest,26,2015-08-07 09:54:46 -0700,NaN
2,No candidate mentioned,Neutral,None of the above,PussssyCroook,27,2015-08-07 09:54:46 -0700,NaN
3,No candidate mentioned,Positive,None of the above,MattFromTexas31,138,2015-08-07 09:54:45 -0700,Texas
4,Donald Trump,Positive,None of the above,sharonDay5,156,2015-08-07 09:54:45 -0700,NaN

In [15]:
sentimientos.groupby('candidate').count()

,id,candidate_confidence,relevant_yn,relevant_yn_confidence,sentiment,sentiment_confidence,subject_matter,subject_matter_confidence,candidate_gold,name,relevant_yn_gold,retweet_count,sentiment_gold,subject_matter_gold,text,tweet_coord,tweet_created,tweet_id,tweet_location,user_timezone
candidate,,,,,,,,,,,,,,,,,,,,
Ben Carson,404,404,404,404,404,404,396,404,0,404,0,404,0,0,404,1,404,404,287,270
Chris Christie,293,293,293,293,293,293,288,293,0,293,0,293,0,0,293,0,293,293,188,177
Donald Trump,2813,2813,2813,2813,2813,2813,2747,2813,7,2813,7,2813,0,4,2813,5,2813,2813,2007,1846
Jeb Bush,705,705,705,705,705,705,693,705,2,705,2,705,1,1,705,0,705,705,495,455
John Kasich,242,242,242,242,242,242,239,242,1,242,1,242,0,0,242,0,242,242,186,170
Marco Rubio,275,275,275,275,275,275,270,275,2,275,2,275,2,0,275,1,275,275,196,182
Mike Huckabee,393,393,393,393,393,393,386,393,3,393,3,393,1,2,393,0,393,393,308,296
No candidate mentioned,7491,7491,7491,7491,7491,7491,7338,7491,10,7491,14,7491,9,10,7491,13,7491,7491,5418,5264
Rand Paul,263,263,263,263,263,263,260,263,0,263,0,263,0,0,263,1,263,263,187,191
Scott Walker,259,259,259,259,259,259,250,259,1,259,1,259,0,1,259,0,259,259,186,173
Ted Cruz,637,637,637,637,637,637,630,637,2,637,2,637,2,0,637,0,637,637,432,388

In [16]:
sentimientos_filtrado['candidate']

0        No candidate mentioned
1                  Scott Walker
2        No candidate mentioned
3        No candidate mentioned
4                  Donald Trump
                  ...
13866    No candidate mentioned
13867             Mike Huckabee
13868                  Ted Cruz
13869              Donald Trump
13870                  Ted Cruz
Name: candidate, Length: 13871, dtype: object

In [17]:
import seaborn as sb

In [18]:
sentimientos_filtrado['candidate'].unique()

array(['No candidate mentioned', 'Scott Walker', 'Donald Trump',
       'Ted Cruz', 'Ben Carson', 'Mike Huckabee', 'Jeb Bush',
       'Chris Christie', 'Marco Rubio', nan, 'Rand Paul', 'John Kasich'],
      dtype=object)

In [19]:
# linea de cÃ³digo (1)
candidatos = sentimientos_filtrado['candidate'].unique()
candidatos

array(['No candidate mentioned', 'Scott Walker', 'Donald Trump',
       'Ted Cruz', 'Ben Carson', 'Mike Huckabee', 'Jeb Bush',
       'Chris Christie', 'Marco Rubio', nan, 'Rand Paul', 'John Kasich'],
      dtype=object)

In [20]:
type(candidatos)

numpy.ndarray

In [21]:
candidatos.shape

(12,)

In [22]:
candidatos_pd = pd.DataFrame(candidatos)
candidatos_pd

                         0
0   No candidate mentioned
1             Scott Walker
2             Donald Trump
3                 Ted Cruz
4               Ben Carson
5            Mike Huckabee
6                 Jeb Bush
7           Chris Christie
8              Marco Rubio
9                      NaN
10               Rand Paul
11             John Kasich

In [33]:
# linea de cÃ³digo (2)
candidatos_totales=candidatos_pd.drop([0,9])
candidatos_totales.reset_index()

   index               0
0      1    Scott Walker
1      2    Donald Trump
2      3        Ted Cruz
3      4      Ben Carson
4      5   Mike Huckabee
5      6        Jeb Bush
6      7  Chris Christie
7      8     Marco Rubio
8     10       Rand Paul
9     11     John Kasich

In [42]:
# linea de cÃ³digo (3)
sentimientos.groupby('candidate').count().sort_values(by = 'id')
# en esta linea le digo que agrupe por candidato y luego cuente los tweets que tiene
# cada candidato

,id,candidate_confidence,relevant_yn,relevant_yn_confidence,sentiment,sentiment_confidence,subject_matter,subject_matter_confidence,candidate_gold,name,relevant_yn_gold,retweet_count,sentiment_gold,subject_matter_gold,text,tweet_coord,tweet_created,tweet_id,tweet_location,user_timezone
candidate,,,,,,,,,,,,,,,,,,,,
John Kasich,242,242,242,242,242,242,239,242,1,242,1,242,0,0,242,0,242,242,186,170
Scott Walker,259,259,259,259,259,259,250,259,1,259,1,259,0,1,259,0,259,259,186,173
Rand Paul,263,263,263,263,263,263,260,263,0,263,0,263,0,0,263,1,263,263,187,191
Marco Rubio,275,275,275,275,275,275,270,275,2,275,2,275,2,0,275,1,275,275,196,182
Chris Christie,293,293,293,293,293,293,288,293,0,293,0,293,0,0,293,0,293,293,188,177
Mike Huckabee,393,393,393,393,393,393,386,393,3,393,3,393,1,2,393,0,393,393,308,296
Ben Carson,404,404,404,404,404,404,396,404,0,404,0,404,0,0,404,1,404,404,287,270
Ted Cruz,637,637,637,637,637,637,630,637,2,637,2,637,2,0,637,0,637,637,432,388
Jeb Bush,705,705,705,705,705,705,693,705,2,705,2,705,1,1,705,0,705,705,495,455
Donald Trump,2813,2813,2813,2813,2813,2813,2747,2813,7,2813,7,2813,0,4,2813,5,2813,2813,2007,1846
No candidate mentioned,7491,7491,7491,7491,7491,7491,7338,7491,10,7491,14,7491,9,10,7491,13,7491,7491,5418,5264

In [23]:
candidatos_pd.count()

0    11
dtype: int64

In [24]:
numero_de_candidatos = candidatos_pd.count() - 2 + 1
numero_de_candidatos
#Â resto dos por que hay un nan y un no se menciona candidato y sumo uno por el indice de python

0    10
dtype: int64

In [25]:
(sentimientos.groupby(['sentiment','candidate'])
             .count()
             .reset_index()
             .sort_values(by=['sentiment','id']))
# hay un indicio de que a mÃ¡s tweets hay mayor probabilidad de ganar una elecciÃ³n

,sentiment,candidate,id,candidate_confidence,relevant_yn,relevant_yn_confidence,sentiment_confidence,subject_matter,subject_matter_confidence,candidate_gold,...,relevant_yn_gold,retweet_count,sentiment_gold,subject_matter_gold,text,tweet_coord,tweet_created,tweet_id,tweet_location,user_timezone
4,Negative,John Kasich,82,82,82,82,82,82,82,1,...,1,82,0,0,82,0,82,82,63,59
5,Negative,Marco Rubio,105,105,105,105,105,102,105,0,...,0,105,0,0,105,0,105,105,82,72
8,Negative,Rand Paul,148,148,148,148,148,146,148,0,...,0,148,0,0,148,1,148,148,96,107
9,Negative,Scott Walker,179,179,179,179,179,175,179,1,...,1,179,0,1,179,0,179,179,126,115
0,Negative,Ben Carson,186,186,186,186,186,182,186,0,...,0,186,0,0,186,0,186,186,133,133
1,Negative,Chris Christie,218,218,218,218,218,215,218,0,...,0,218,0,0,218,0,218,218,138,125
10,Negative,Ted Cruz,221,221,221,221,221,218,221,0,...,0,221,0,0,221,0,221,221,156,145
6,Negative,Mike Huckabee,237,237,237,237,237,232,237,2,...,2,237,1,2,237,0,237,237,181,181
3,Negative,Jeb Bush,589,589,589,589,589,579,589,2,...,2,589,1,1,589,0,589,589,405,369
2,Negative,Donald Trump,1758,1758,1758,1758,1758,1715,1758,4,...,4,1758,0,1,1758,4,1758,1758,1265,1158
7,Negative,No candidate mentioned,4724,4724,4724,4724,4724,4633,4724,8,...,11,4724,9,7,4724,6,4724,4724,3338,3231
20,Neutral,Scott Walker,38,38,38,38,38,35,38,0,...,0,38,0,0,38,0,38,38,30,28
12,Neutral,Chris Christie,42,42,42,42,42,42,42,0,...,0,42,0,0,42,0,42,42,29,32
15,Neutral,John Kasich,47,47,47,47,47,45,47,0,...,0,47,0,0,47,0,47,47,34,31
16,Neutral,Marco Rubio,51,51,51,51,51,50,51,0,...,0,51,0,0,51,1,51,51,29,33
11,Neutral,Ben Carson,54,54,54,54,54,52,54,0,...,0,54,0,0,54,0,54,54,38,33
19,Neutral,Rand Paul,60,60,60,60,60,59,60,0,...,0,60,0,0,60,0,60,60,45,42
14,Neutral,Jeb Bush,72,72,72,72,72,70,72,0,...,0,72,0,0,72,0,72,72,54,50
17,Neutral,Mike Huckabee,83,83,83,83,83,81,83,0,...,0,83,0,0,83,0,83,83,70,60
21,Neutral,Ted Cruz,126,126,126,126,126,124,126,0,...,0,126,0,0,126,0,126,126,81,79
13,Neutral,Donald Trump,446,446,446,446,446,432,446,2,...,2,446,0,2,446,1,446,446,326,315
18,Neutral,No candidate mentioned,2087,2087,2087,2087,2087,2044,2087,1,...,1,2087,0,1,2087,6,2087,2087,1583,1568
23,Positive,Chris Christie,33,33,33,33,33,31,33,0,...,0,33,0,0,33,0,33,33,21,20
31,Positive,Scott Walker,42,42,42,42,42,40,42,0,...,0,42,0,0,42,0,42,42,30,30
25,Positive,Jeb Bush,44,44,44,44,44,44,44,0,...,0,44,0,0,44,0,44,44,36,36
30,Positive,Rand Paul,55,55,55,55,55,55,55,0,...,0,55,0,0,55,0,55,55,46,42
28,Positive,Mike Huckabee,73,73,73,73,73,73,73,1,...,1,73,0,0,73,0,73,73,57,55
26,Positive,John Kasich,113,113,113,113,113,112,113,0,...,0,113,0,0,113,0,113,113,89,80
27,Positive,Marco Rubio,119,119,119,119,119,118,119,2,...,2,119,2,0,119,0,119,119,85,77
22,Positive,Ben Carson,164,164,164,164,164,162,164,0,...,0,164,0,0,164,1,164,164,116,104
32,Positive,Ted Cruz,290,290,290,290,290,288,290,2,...,2,290,2,0,290,0,290,290,195,164
24,Positive,Donald Trump,609,609,609,609,609,600,609,1,...,1,609,0,1,609,0,609,609,416,373
29,Positive,No candidate mentioned,680,680,680,680,680,661,680,1,...,2,680,0,2,680,1,680,680,497,465

In [43]:
# linea de cÃ³digo (4)
(sentimientos.groupby('sentiment')
             .count())
# con estas lineas le digo que agrupe usando la columna sentimiento y luego haga 
# conteo de el sentimiento en cada caso

,id,candidate,candidate_confidence,relevant_yn,relevant_yn_confidence,sentiment_confidence,subject_matter,subject_matter_confidence,candidate_gold,name,relevant_yn_gold,retweet_count,sentiment_gold,subject_matter_gold,text,tweet_coord,tweet_created,tweet_id,tweet_location,user_timezone
sentiment,,,,,,,,,,,,,,,,,,,,
Negative,8493,8447,8493,8493,8493,8493,8302,8493,18,8493,21,8493,11,12,8493,11,8493,8493,6016,5722
Neutral,3142,3106,3142,3142,3142,3142,3050,3142,3,3142,3,3142,0,3,3142,8,3142,3142,2343,2290
Positive,2236,2222,2236,2236,2236,2236,2193,2236,7,2236,8,2236,4,3,2236,2,2236,2236,1600,1456

In [27]:
# liena de cÃ³digo (5)
(sentimientos.groupby(['candidate','sentiment'])
             .count())
# Aqui agrupo por primero por candidato y luego por el sentimiento que causan los
# tweets donde se menciona ese candidato.

#             .reset_index()
#             .sort_values(by=['sentiment','id']))

                                    id  candidate_confidence  relevant_yn  \
candidate              sentiment
Ben Carson             Negative    186                   186          186
                       Neutral      54                    54           54
                       Positive    164                   164          164
Chris Christie         Negative    218                   218          218
                       Neutral      42                    42           42
                       Positive     33                    33           33
Donald Trump           Negative   1758                  1758         1758
                       Neutral     446                   446          446
                       Positive    609                   609          609
Jeb Bush               Negative    589                   589          589
                       Neutral      72                    72           72
                       Positive     44                    44           44
John Kasich            Negative     82                    82           82
                       Neutral      47                    47           47
                       Positive    113                   113          113
Marco Rubio            Negative    105                   105          105
                       Neutral      51                    51           51
                       Positive    119                   119          119
Mike Huckabee          Negative    237                   237          237
                       Neutral      83                    83           83
                       Positive     73                    73           73
No candidate mentioned Negative   4724                  4724         4724
                       Neutral    2087                  2087         2087
                       Positive    680                   680          680
Rand Paul              Negative    148                   148          148
                       Neutral      60                    60           60
                       Positive     55                    55           55
Scott Walker           Negative    179                   179          179
                       Neutral      38                    38           38
                       Positive     42                    42           42
Ted Cruz               Negative    221                   221          221
                       Neutral     126                   126          126
                       Positive    290                   290          290

                                  relevant_yn_confidence  \
candidate              sentiment
Ben Carson             Negative                      186
                       Neutral                        54
                       Positive                      164
Chris Christie         Negative                      218
                       Neutral                        42
                       Positive                       33
Donald Trump           Negative                     1758
                       Neutral                       446
                       Positive                      609
Jeb Bush               Negative                      589
                       Neutral                        72
                       Positive                       44
John Kasich            Negative                       82
                       Neutral                        47
                       Positive                      113
Marco Rubio            Negative                      105
                       Neutral                        51
                       Positive                      119
Mike Huckabee          Negative                      237
                       Neutral                        83
                       Positive                       73
No candidate mentioned Negative                     4724
                       Neutral                      2087
                       Positive                      680
Rand Paul              Negative                      148
                       Neutral                        60
                       Positive                       55
Scott Walker           Negative                      179
                       Neutral                        38
                       Positive                       42
Ted Cruz               Negative                      221
                       Neutral                       126
                       Positive                      290

                                  sentiment_confidence  subject_matter  \
candidate              sentiment
Ben Carson             Negative                    186             182
                       Neutral                      54              52
                       Positive                    164             162
Chris Christie         Negative                    218             215
                       Neutral                      42              42
                       Positive                     33              31
Donald Trump           Negative                   1758            1715
                       Neutral                     446             432
                       Positive                    609             600
Jeb Bush               Negative                    589             579
                       Neutral                      72              70
                       Positive                     44              44
John Kasich            Negative                     82              82
                       Neutral                      47              45
                       Positive                    113             112
Marco Rubio            Negative                    105             102
                       Neutral                      51              50
                       Positive                    119             118
Mike Huckabee          Negative                    237             232
                       Neutral                      83              81
                       Positive                     73              73
No candidate mentioned Negative                   4724            4633
                       Neutral                    2087            2044
                       Positive                    680             661
Rand Paul              Negative                    148             146
                       Neutral                      60              59
                       Positive                     55              55
Scott Walker           Negative                    179             175
                       Neutral                      38              35
                       Positive                     42              40
Ted Cruz               Negative                    221             218
                       Neutral                     126             124
                       Positive                    290             288

                                  subject_matter_confidence  candidate_gold  \
candidate              sentiment
Ben Carson             Negative                         186               0
                       Neutral                           54               0
                       Positive                         164               0
Chris Christie         Negative                         218               0
                       Neutral                           42               0
                       Positive                          33               0
Donald Trump           Negative                        1758               4
                       Neutral                          446               2
                       Positive                         609               1
Jeb Bush               Negative                         589               2
                       Neutral                           72               0
                       Positive                          44               0
John Kasich            Negative                          82               1
                       Neutral                           47               0
                       Positive                         113               0
Marco Rubio            Negative                         105               0
                       Neutral                           51               0
                       Positive                         119               2
Mike Huckabee          Negative                         237               2
                       Neutral                           83               0
                       Positive                          73               1
No candidate mentioned Negative                        4724               8
                       Neutral                         2087               1
                       Positive                         680               1
Rand Paul              Negative                         148               0
                       Neutral                           60               0
                       Positive                          55               0
Scott Walker           Negative                         179               1
                       Neutral                           38               0
                       Positive                          42               0
Ted Cruz               Negative                         221               0
                       Neutral                          126               0
                       Positive                         290               2

                                  name  relevant_yn_gold  retweet_count  \
candidate              sentiment
Ben Carson             Negative    186                 0            186
                       Neutral      54                 0             54
                       Positive    164                 0            164
Chris Christie         Negative    218                 0            218
                       Neutral      42                 0             42
                       Positive     33                 0             33
Donald Trump           Negative   1758                 4           1758
                       Neutral     446                 2            446
                       Positive    609                 1            609
Jeb Bush               Negative    589                 2            589
                       Neutral      72                 0             72
                       Positive     44                 0             44
John Kasich            Negative     82                 1             82
                       Neutral      47                 0             47
                       Positive    113                 0            113
Marco Rubio            Negative    105                 0            105
                       Neutral      51                 0             51
                       Positive    119                 2            119
Mike Huckabee          Negative    237                 2            237
                       Neutral      83                 0             83
                       Positive     73                 1             73
No candidate mentioned Negative   4724                11           4724
                       Neutral    2087                 1           2087
                       Positive    680                 2            680
Rand Paul              Negative    148                 0            148
                       Neutral      60                 0             60
                       Positive     55                 0             55
Scott Walker           Negative    179                 1            179
                       Neutral      38                 0             38
                       Positive     42                 0             42
Ted Cruz               Negative    221                 0            221
                       Neutral     126                 0            126
                       Positive    290                 2            290

                                  sentiment_gold  subject_matter_gold  text  \
candidate              sentiment
Ben Carson             Negative                0                    0   186
                       Neutral                 0                    0    54
                       Positive                0                    0   164
Chris Christie         Negative                0                    0   218
                       Neutral                 0                    0    42
                       Positive                0                    0    33
Donald Trump           Negative                0                    1  1758
                       Neutral                 0                    2   446
                       Positive                0                    1   609
Jeb Bush               Negative                1                    1   589
                       Neutral                 0                    0    72
                       Positive                0                    0    44
John Kasich            Negative                0                    0    82
                       Neutral                 0                    0    47
                       Positive                0                    0   113
Marco Rubio            Negative                0                    0   105
                       Neutral                 0                    0    51
                       Positive                2                    0   119
Mike Huckabee          Negative                1                    2   237
                       Neutral                 0                    0    83
                       Positive                0                    0    73
No candidate mentioned Negative                9                    7  4724
                       Neutral                 0                    1  2087
                       Positive                0                    2   680
Rand Paul              Negative                0                    0   148
                       Neutral                 0                    0    60
                       Positive                0                    0    55
Scott Walker           Negative                0                    1   179
                       Neutral                 0                    0    38
                       Positive                0                    0    42
Ted Cruz               Negative                0                    0   221
                       Neutral                 0                    0   126
                       Positive                2                    0   290

                                  tweet_coord  tweet_created  tweet_id  \
candidate              sentiment
Ben Carson             Negative             0            186       186
                       Neutral              0             54        54
                       Positive             1            164       164
Chris Christie         Negative             0            218       218
                       Neutral              0             42        42
                       Positive             0             33        33
Donald Trump           Negative             4           1758      1758
                       Neutral              1            446       446
                       Positive             0            609       609
Jeb Bush               Negative             0            589       589
                       Neutral              0             72        72
                       Positive             0             44        44
John Kasich            Negative             0             82        82
                       Neutral              0             47        47
                       Positive             0            113       113
Marco Rubio            Negative             0            105       105
                       Neutral              1             51        51
                       Positive             0            119       119
Mike Huckabee          Negative             0            237       237
                       Neutral              0             83        83
                       Positive             0             73        73
No candidate mentioned Negative             6           4724      4724
                       Neutral              6           2087      2087
                       Positive             1            680       680
Rand Paul              Negative             1            148       148
                       Neutral              0             60        60
                       Positive             0             55        55
Scott Walker           Negative             0            179       179
                       Neutral              0             38        38
                       Positive             0             42        42
Ted Cruz               Negative             0            221       221
                       Neutral              0            126       126
                       Positive             0            290       290

                                  tweet_location  user_timezone
candidate              sentiment
Ben Carson             Negative              133            133
                       Neutral                38             33
                       Positive              116            104
Chris Christie         Negative              138            125
                       Neutral                29             32
                       Positive               21             20
Donald Trump           Negative             1265           1158
                       Neutral               326            315
                       Positive              416            373
Jeb Bush               Negative              405            369
                       Neutral                54             50
                       Positive               36             36
John Kasich            Negative               63             59
                       Neutral                34             31
                       Positive               89             80
Marco Rubio            Negative               82             72
                       Neutral                29             33
                       Positive               85             77
Mike Huckabee          Negative              181            181
                       Neutral                70             60
                       Positive               57             55
No candidate mentioned Negative             3338           3231
                       Neutral              1583           1568
                       Positive              497            465
Rand Paul              Negative               96            107
                       Neutral                45             42
                       Positive               46             42
Scott Walker           Negative              126            115
                       Neutral                30             28
                       Positive               30             30
Ted Cruz               Negative              156            145
                       Neutral                81             79
                       Positive              195            164